<option value="Baucan Norte">Baucan Norte</option>
<option value="Baucan Sur">Baucan Sur</option>
<option value="Boctol">Boctol</option>
<option value="Boyog Norte">Boyog Norte</option>
<option value="Boyog Proper">Boyog Proper</option>
<option value="Boyog Sur">Boyog Sur</option>
<option value="Cabad">Cabad</option>
<option value="Candasig">Candasig</option>
<option value="Cantalid">Cantalid</option>
<option value="Cantomimbo">Cantomimbo</option>
<option value="Cogon">Cogon</option>
<option value="Datag Norte">Datag Norte</option>
<option value="Datag Sur">Datag Sur</option>
<option value="Del Carmen Este">Del Carmen Este</option>
<option value="Del Carmen Norte">Del Carmen Norte</option>
<option value="Del Carmen Sur">Del Carmen Sur</option>
<option value="Del Carmen Weste">Del Carmen Weste</option>
<option value="Del Rosario">Del Rosario</option>
<option value="Dorol">Dorol</option>
<option value="Haguilanan Grande">Haguilanan Grande</option>
<option value="Hanopol Este">Hanopol Este</option>
<option value="Hanopol Norte">Hanopol Norte</option>
<option value="Hanopol Weste">Hanopol Weste</option>
<option value="Magsija">Magsija</option>
<option value="Maslog">Maslog</option>
<option value="Sagasa">Sagasa</option>
<option value="Sal-ing">Sal-ing</option>
<option value="San Isidro">San Isidro</option>
<option value="San Roque">San Roque</option>
<option value="Santo Niño">Santo Niño</option>
<option value="Tagustusan">Tagustusan</option>