<option value="Anonang">Anonang</option>
<option value="Asinan">Asinan</option>
<option value="Bago">Bago</option>
<option value="Baluarte">Baluarte</option>
<option value="Bantuan">Bantuan</option>
<option value="Bato">Bato</option>
<option value="Bonotbonot">Bonotbonot</option>
<option value="Bugaong">Bugaong</option>
<option value="Cambuhat">Cambuhat</option>
<option value="Cambus-oc">Cambus-oc</option>
<option value="Cangawa">Cangawa</option>
<option value="Cantomugcad">Cantomugcad</option>
<option value="Cantores">Cantores</option>
<option value="Cantuba">Cantuba</option>
<option value="Catigbian">Catigbian</option>
<option value="Cawag">Cawag</option>
<option value="Cruz">Cruz</option>
<option value="Dait">Dait</option>
<option value="Eastern Cabul-an">Eastern Cabul-an</option>
<option value="Hunan">Hunan</option>
<option value="Lapacan Norte">Lapacan Norte</option>
<option value="Lapacan Sur">Lapacan Sur</option>
<option value="Lubang">Lubang</option>
<option value="Lusong">Lusong</option>
<option value="Magkaya">Magkaya</option>
<option value="Merryland">Merryland</option>
<option value="Nueva Granada">Nueva Granada</option>
<option value="Nueva Montana">Nueva Montana</option>
<option value="Overland">Overland</option>
<option value="Panghabgan">Panghabgan</option>
<option value="Poblacion">Poblacion</option>
<option value="Puting Bato">Puting Bato</option>
<option value="Rufo Hill">Rufo Hill</option>
<option value="Sweetland">Sweetland</option>
<option value="Western Cabul-an">Western Cabul-an</option>