<option value="Alegria">Alegria</option>
<option value="Bicao">Bicao</option>
<option value="Buenavista">Buenavista</option>
<option value="Buenos Aires">Buenos Aires</option>
<option value="Calatrava">Calatrava</option>
<option value="El Progreso">El Progreso</option>
<option value="El Salvador">El Salvador</option>
<option value="Guadalupe">Guadalupe</option>
<option value="Katipunan">Katipunan</option>
<option value="La Libertad">La Libertad</option>
<option value="La Paz">La Paz</option>
<option value="La Salvacion">La Salvacion</option>
<option value="La Victoria">La Victoria</option>
<option value="Matin-ao">Matin-ao</option>
<option value="Montehermoso">Montehermoso</option>
<option value="Montesuerte">Montesuerte</option>
<option value="Montesunting">Montesunting</option>
<option value="Montevideo">Montevideo</option>
<option value="Nueva Fuerza">Nueva Fuerza</option>
<option value="Nueva Vida Este">Nueva Vida Este</option>
<option value="Nueva Vida Norte">Nueva Vida Norte</option>
<option value="Nueva Vida Sur">Nueva Vida Sur</option>
<option value="Poblacion Norte">Poblacion Norte</option>
<option value="Poblacion Sur">Poblacion Sur</option>
<option value="Tambo-an">Tambo-an</option>
<option value="Vallehermoso">Vallehermoso</option>
<option value="Villaflor">Villaflor</option>
<option value="Villafuerte">Villafuerte</option>
<option value="Villarcayo">Villarcayo</option>
