<option value="Alegria">Alegria</option>
<option value="Ambuan">Ambuan</option>
<option value="Baang">Baang</option>
<option value="Bagtic">Bagtic</option>
<option value="Bongbong">Bongbong</option>
<option value="Cambailan">Cambailan</option>
<option value="Candumayao">Candumayao</option>
<option value="Causwagan Norte">Causwagan Norte</option>
<option value="Hagbuaya">Hagbuaya</option>
<option value="Haguilanan">Haguilanan</option>
<option value="Kang-iras">Kang-iras</option>
<option value="Libertad Sur">Libertad Sur</option>
<option value="Liboron">Liboron</option>
<option value="Mahayag Norte">Mahayag Norte</option>
<option value="Mahayag Sur">Mahayag Sur</option>
<option value="Maitum">Maitum</option>
<option value="Mantasida">Mantasida</option>
<option value="Poblacion Weste">Poblacion Weste</option>
<option value="Poblacion">Poblacion</option>
<option value="Rizal">Rizal</option>
<option value="Sinakayanan">Sinakayanan</option>
<option value="Triple Union">Triple Union</option>