<option value="Basdio">Basdio</option>
<option value="Bato">Bato</option>
<option value="Bayong">Bayong</option>
<option value="Biabas">Biabas</option>
<option value="Bulawan">Bulawan</option>
<option value="Cabantian">Cabantian</option>
<option value="Canhaway">Canhaway</option>
<option value="Cansiwang">Cansiwang</option>
<option value="Casbu">Casbu</option>
<option value="Catungawan Norte">Catungawan Norte</option>
<option value="Catungawan Sur">Catungawan Sur</option>
<option value="Guinacot">Guinacot</option>
<option value="Guio-ang">Guio-ang</option>
<option value="Lombog">Lombog</option>
<option value="Mayuga">Mayuga</option>
<option value="Sawang">Sawang</option>
<option value="Tabajan">Tabajan</option>
<option value="Tabunok">Tabunok</option>
<option value="Trinidad">Trinidad</option>