<option value="Anonang">Anonang</option>
<option value="Badiang">Badiang</option>
<option value="Baguhan">Baguhan</option>
<option value="Bahan">Bahan</option>
<option value="Banahao">Banahao</option>
<option value="Baogo">Baogo</option>
<option value="Bugang">Bugang</option>
<option value="Cagawasan">Cagawasan</option>
<option value="Cagayan">Cagayan</option>
<option value="Cambitoon">Cambitoon</option>
<option value="Canlinte">Canlinte</option>
<option value="Cawayan">Cawayan</option>
<option value="Cogon">Cogon</option>
<option value="Cuaming">Cuaming</option>
<option value="Dagnawan">Dagnawan</option>
<option value="Dagohoy">Dagohoy</option>
<option value="Dait Sur">Dait Sur</option>
<option value="Datag">Datag</option>
<option value="Fatima">Fatima</option>
<option value="Hambongan">Hambongan</option>
<option value="Ilaud">Ilaud</option>
<option value="Ilaya">Ilaya</option>
<option value="Ilihan">Ilihan</option>
<option value="Lapacan Norte">Lapacan Norte</option>
<option value="Lapacan Sur">Lapacan Sur</option>
<option value="Lawis">Lawis</option>
<option value="Liloan Norte">Liloan Norte</option>
<option value="Liloan Sur">Liloan Sur</option>
<option value="Lomboy">Lomboy</option>
<option value="Lonoy Cainisican">Lonoy Cainisican</option>
<option value="Lonoy Roma">Lonoy Roma</option>
<option value="Lutao">Lutao</option>
<option value="Luyo">Luyo</option>
<option value="Mabuhay">Mabuhay</option>
<option value="Maria Rosario">Maria Rosario</option>
<option value="Nabuad">Nabuad</option>
<option value="Napo">Napo</option>
<option value="Ondol">Ondol</option>
<option value="Poblacion">Poblacion</option>
<option value="Riverside">Riverside</option>
<option value="Saa">Saa</option>
<option value="San Isidro">San Isidro</option>
<option value="San Jose">San Jose</option>
<option value="Santo Niño">Santo Niño</option>
<option value="Santo Rosario">Santo Rosario</option>
<option value="Sua">Sua</option>
<option value="Tambook">Tambook</option>
<option value="Tungod">Tungod</option>
<option value="Ubujan">Ubujan</option>
<option value="U-og">U-og</option>