<option value="Agape">Agape</option>
<option value="Alegria">Alegria</option>
<option value="Bagumbayan">Bagumbayan</option>
<option value="Bahian">Bahian</option>
<option value="Bonbon Lower">Bonbon Lower</option>
<option value="Bonbon Upper">Bonbon Upper</option>
<option value="Buenavista">Buenavista</option>
<option value="Bugho">Bugho</option>
<option value="Cabadiangan">Cabadiangan</option>
<option value="Calunasan Norte">Calunasan Norte</option>
<option value="Calunasan Sur">Calunasan Sur</option>
<option value="Camayaan">Camayaan</option>
<option value="Cambance">Cambance</option>
<option value="Candabong">Candabong</option>
<option value="Candasag">Candasag</option>
<option value="Canlasid">Canlasid</option>
<option value="Gon-ob">Gon-ob</option>
<option value="Gotozon">Gotozon</option>
<option value="Jimilian">Jimilian</option>
<option value="Oy">Oy</option>
<option value="Poblacion Ondol">Poblacion Ondol</option>
<option value="Poblacion Sawang">Poblacion Sawang</option>
<option value="Quinoguitan">Quinoguitan</option>
<option value="Taytay">Taytay</option>
<option value="Tigbao">Tigbao</option>
<option value="Ugpong">Ugpong</option>
<option value="Valladolid">Valladolid</option>
<option value="Villaflor">Villaflor</option>