<option value="Abaca">Abaca</option>
<option value="Abad Santos">Abad Santos</option>
<option value="Aguipo">Aguipo</option>
<option value="Baybayon">Baybayon</option>
<option value="Bulawan">Bulawan</option>
<option value="Cabidian">Cabidian</option>
<option value="Cawayanan">Cawayanan</option>
<option value="Concepcion (Banlas)">Concepcion (Banlas)</option>
<option value="Del Mar">Del Mar</option>
<option value="Lungsoda-an">Lungsoda-an</option>
<option value="Marcelo">Marcelo</option>
<option value="Minol">Minol</option>
<option value="Paraiso">Paraiso</option>
<option value="Poblacion I">Poblacion I</option>
<option value="Poblacion II">Poblacion II</option>
<option value="San Isidro">San Isidro</option>
<option value="San Jose">San Jose</option>
<option value="San Rafael">San Rafael</option>
<option value="San Roque (Cabulao)">San Roque (Cabulao)</option>
<option value="Tambo">Tambo</option>
<option value="Tangkigan">Tangkigan</option>
<option value="Valaga">Valaga</option>