<option value="Aguining">Aguining</option>
<option value="Basiao">Basiao</option>
<option value="Baud">Baud</option>
<option value="Bayog">Bayog</option>
<option value="Bogo">Bogo</option>
<option value="Bonbonon">Bonbonon</option>
<option value="Butan">Butan</option>
<option value="Campamanog">Campamanog</option>
<option value="Canmangao">Canmangao</option>
<option value="Gaus">Gaus</option>
<option value="Kabangkalan">Kabangkalan</option>
<option value="Lapinig">Lapinig</option>
<option value="Lipata">Lipata</option>
<option value="Poblacion">Poblacion</option>
<option value="Popoo">Popoo</option>
<option value="Saguise">Saguise</option>
<option value="San Jose">San Jose</option>
<option value="San Vicente">San Vicente</option>
<option value="Santo Rosario">Santo Rosario</option>
<option value="Tilmobo">Tilmobo</option>
<option value="Tugas">Tugas</option>
<option value="Tugnao">Tugnao</option>
<option value="Villa Milagrosa">Villa Milagrosa</option>