<option value="Calangahan">Calangahan</option>
<option value="Canmao">Canmao</option>
<option value="Canmaya Centro">Canmaya Centro</option>
<option value="Canmaya Diot">Canmaya Diot</option>
<option value="Dagnawan">Dagnawan</option>
<option value="kabasacan">kabasacan</option>
<option value="Kagawasan">Kagawasan</option>
<option value="Katipunan">Katipunan</option>
<option value="Langtad">Langtad</option>
<option value="Libertad Norte">Libertad Norte</option>
<option value="Libertad Sur">Libertad Sur</option>
<option value="Mantalongon">Mantalongon</option>
<option value="Poblacion">Poblacion</option>
<option value="Sagbayan Sur">Sagbayan Sur</option>
<option value="San Agustin">San Agustin</option>
<option value="San Antonio">San Antonio</option>
<option value="San Isidro">San Isidro</option>
<option value="San Ramon">San Ramon</option>
<option value="San Roque">San Roque</option>
<option value="San Vicente Norte">San Vicente Norte</option>
<option value="San Vicente Sur">San Vicente Sur</option>
<option value="Santa Catalina">Santa Catalina</option>
<option value="Santa Cruz">Santa Cruz</option>
<option value="Ubojan">Ubojan</option>