<option value="Bool">Bool</option>
<option value="Booy">Booy</option>
<option value="Cabawan">Cabawan</option>
<option value="Cogon">Cogon</option>
<option value="Dampas">Dampas</option>
<option value="Dao">Dao</option>
<option value="Manga">Manga</option>
<option value="Mansasa">Mansasa</option>
<option value="Poblacion I">Poblacion I</option>
<option value="Poblacion II">Poblacion II</option>
<option value="Poblacion III">Poblacion III</option>
<option value="San Isidro">San Isidro</option>
<option value="Taloto">Taloto</option>
<option value="Tiptip">Tiptip</option>
<option value="Ubujan">Ubujan</option>