<option value="Bagacay">Bagacay</option>
<option value="Balintawak">Balintawak</option>
<option value="Burgos">Burgos</option>
<option value="Busalian">Busalian</option>
<option value="Calituban">Calituban</option>
<option value="Cataban">Cataban</option>
<option value="Guindacpan">Guindacpan</option>
<option value="Magsaysay">Magsaysay</option>
<option value="Mahanay">Mahanay</option>
<option value="Nocnocan">Nocnocan</option>
<option value="Poblacion">Poblacion</option>
<option value="Rizal">Rizal</option>
<option value="Sag">Sag</option>
<option value="San Agustin">San Agustin</option>
<option value="San Carlos">San Carlos</option>
<option value="San Francisco">San Francisco</option>
<option value="San Isidro">San Isidro</option>
<option value="San Jose">San Jose</option>
<option value="San Pedro">San Pedro</option>
<option value="Santo Niño">Santo Niño</option>
<option value="Sikatuna">Sikatuna</option>
<option value="Suba">Suba</option>
<option value="Tanghaligue">Tanghaligue</option>
<option value="Zamora">Zamora</option>