<option value="Adlawan">Adlawan</option>
<option value="Anas">Anas</option>
<option value="Anonang">Anonang</option>
<option value="Anoyon">Anoyon</option>
<option value="Balingasao">Balingasao</option>
<option value="Banderaahan (Upper Ginopolan)">Banderaahan (Upper Ginopolan)</option>
<option value="Botong">Botong</option>
<option value="Buyog">Buyog</option>
<option value="Canduao Occidental">Canduao Occidental</option>
<option value="Canduao Oriental">Canduao Oriental</option>
<option value="Canlusong">Canlusong</option>
<option value="Canmanico">Canmanico</option>
<option value="Cansibao">Cansibao</option>
<option value="Catug-a">Catug-a</option>
<option value="Cutcutan">Cutcutan</option>
<option value="Danao">Danao</option>
<option value="Genoveva">Genoveva</option>
<option value="Ginopolan (Ginopolan Proper)">Ginopolan (Ginopolan Proper)</option>
<option value="La Victoria">La Victoria</option>
<option value="Lantang">Lantang</option>
<option value="Limocon">Limocon</option>
<option value="Loctob">Loctob</option>
<option value="Magsaysay">Magsaysay</option>
<option value="Marawis">Marawis</option>
<option value="Maubo">Maubo</option>
<option value="Nailo">Nailo</option>
<option value="Omjon">Omjon</option>
<option value="Pangi-an">Pangi-an</option>
<option value="Poblacion Occidental">Poblacion Occidental</option>
<option value="Poblacion Oriental">Poblacion Oriental</option>
<option value="Simang">Simang</option>
<option value="Taug">Taug</option>
<option value="Tausion">Tausion</option>
<option value="Taytay">Taytay</option>
<option value="Ticum">Ticum</option>