<option value="Abihilan">Abihilan</option>
<option value="Anoling">Anoling</option>
<option value="Boyo-an">Boyo-an</option>
<option value="Cadapdapan">Cadapdapan</option>
<option value="Cambane">Cambane</option>
<option value="Canawa">Canawa</option>
<option value="Can-olin">Can-olin</option>
<option value="Cogtong">Cogtong</option>
<option value="La Union">La Union</option>
<option value="Luan">Luan</option>
<option value="Lungsoda-an">Lungsoda-an</option>
<option value="Mahangin">Mahangin</option>
<option value="Pagahat">Pagahat</option>
<option value="Panadtaran">Panadtaran</option>
<option value="Panas">Panas</option>
<option value="Poblacion">Poblacion</option>
<option value="San Isidro">San Isidro</option>
<option value="Tambongan">Tambongan</option>
<option value="Tawid">Tawid</option>
<option value="Tubod (Tres Rosas)">Tubod (Tres Rosas)</option>
<option value="Tugas">Tugas</option>