<option value="Bacani">Bacani</option>
<option value="Bogtongbod">Bogtongbod</option>
<option value="Bonbon">Bonbon</option>
<option value="Bontud">Bontud</option>
<option value="Buacao">Buacao</option>
<option value="Buangan">Buangan</option>
<option value="Cabog">Cabog</option>
<option value="Caluwasan">Caluwasan</option>
<option value="Candajec">Candajec</option>
<option value="Cantoyoc">Cantoyoc</option>
<option value="Comaang">Comaang</option>
<option value="Danahao">Danahao</option>
<option value="Katipunan">Katipunan</option>
<option value="Lajog">Lajog</option>
<option value="Mataub">Mataub</option>
<option value="Nahawan">Nahawan</option>
<option value="Poblacion Centro">Poblacion Centro</option>
<option value="Poblacion Norte">Poblacion Norte</option>
<option value="Poblacion Sur">Poblacion Sur</option>
<option value="Tangaran">Tangaran</option>
<option value="Tontunan">Tontunan</option>
<option value="Tubod">Tubod</option>
<option value="Villaflor">Villaflor</option>