<option value="Alejawan">Alejawan</option>
<option value="Angilan">Angilan</option>
<option value="Anibongan">Anibongan</option>
<option value="Bangwalog">Bangwalog</option>
<option value="Cansuhay">Cansuhay</option>
<option value="Danao">Danao</option>
<option value="Duay">Duay</option>
<option value="Guinsularan">Guinsularan</option>
<option value="Imelda">Imelda</option>
<option value="Itum">Itum</option>
<option value="Langkis">Langkis</option>
<option value="Lobogon">Lobogon</option>
<option value="Madua Norte">Madua Norte</option>
<option value="Madua Sur">Madua Sur</option>
<option value="Mambool">Mambool</option>
<option value="Mawi">Mawi</option>
<option value="Payao">Payao</option>
<option value="San Antonio">San Antonio</option>
<option value="San Isidro">San Isidro</option>
<option value="San Pedro">San Pedro</option>
<option value="Taytay">Taytay</option>