<option value="Alumar">Alumar</option>
<option value="Banacon">Banacon</option>
<option value="Buyog">Buyog</option>
<option value="Cabasakan">Cabasakan</option>
<option value="Campao Occidental">Campao Occidental</option>
<option value="Campao Oriental">Campao Oriental</option>
<option value="Cangmundo">Cangmundo</option>
<option value="Carlos P. Garcia">Carlos P. Garcia</option>
<option value="Corte Baud">Corte Baud</option>
<option value="Handumon">Handumon</option>
<option value="Jagoliao">Jagoliao</option>
<option value="Jandayan Norte">Jandayan Norte</option>
<option value="Jandayan Sur">Jandayan Sur</option>
<option value="Mahanay Island">Mahanay Island</option>
<option value="Nasingin">Nasingin</option>
<option value="Pandahon">Pandahon</option>
<option value="Poblacion">Poblacion</option>
<option value="Saguise">Saguise</option>
<option value="Salog">Salog</option>
<option value="San Jose">San Jose</option>
<option value="Santo Niño">Santo Niño</option>
<option value="Taytay">Taytay</option>
<option value="Tugas">Tugas</option>
<option value="Tulang">Tulang</option>