<option value="Alejawan">Alejawan</option>
<option value="Balili">Balili</option>
<option value="Boctol">Boctol</option>
<option value="Bunga Ilaya">Bunga Ilaya</option>
<option value="Bunga Mar">Bunga Mar</option>
<option value="Buyog">Buyog</option>
<option value="Cabunga-an">Cabunga-an</option>
<option value="Calabacita">Calabacita</option>
<option value="Cambugason">Cambugason</option>
<option value="Can-ipol">Can-ipol</option>
<option value="Canjulao">Canjulao</option>
<option value="Cantagay">Cantagay</option>
<option value="Cantuyoc">Cantuyoc</option>
<option value="Can-uba">Can-uba</option>
<option value="Can-upao">Can-upao</option>
<option value="Faraon">Faraon</option>
<option value="Ipil">Ipil</option>
<option value="Kinagbaan">Kinagbaan</option>
<option value="Laca">Laca</option>
<option value="Larapan">Larapan</option>
<option value="Lonoy">Lonoy</option>
<option value="Looc">Looc</option>
<option value="Malbog">Malbog</option>
<option value="Mayana">Mayana</option>
<option value="Naatang">Naatang</option>
<option value="Nausok">Nausok</option>
<option value="Odiong">Odiong</option>
<option value="Pagina">Pagina</option>
<option value="Pangdan">Pangdan</option>
<option value="Poblacion (Pondol)">Poblacion (Pondol)</option>
<option value="Tejero">Tejero</option>
<option value="Tubod Mar">Tubod Mar</option>
<option value="Tubod Monte">Tubod Monte</option>