<option value="Banban">Banban</option>
<option value="Bonkokan Ilaya">Bonkokan Ilaya</option>
<option value="Bonkokan Ubos">Bonkokan Ubos</option>
<option value="Calvario">Calvario</option>
<option value="Candulang">Candulang</option>
<option value="Catugasan">Catugasan</option>
<option value="Cayupo">Cayupo</option>
<option value="Cogon">Cogon</option>
<option value="Jambawan">Jambawan</option>
<option value="La Fortuna">La Fortuna</option>
<option value="Lomanoy">Lomanoy</option>
<option value="Macalingan">Macalingan</option>
<option value="Malinao East">Malinao East</option>
<option value="Malinao West">Malinao West</option>
<option value="Nagsulay">Nagsulay</option>
<option value="Poblacion">Poblacion</option>
<option value="Taug">Taug</option>
<option value="Tiguis">Tiguis</option>