<option value="Aurora">Aurora</option>
<option value="Bagacay">Bagacay</option>
<option value="Bagumbayan">Bagumbayan</option>
<option value="Bayong">Bayong</option>
<option value="Buenasuerte">Buenasuerte</option>
<option value="Cagawasan">Cagawasan</option>
<option value="Cansungay">Cansungay</option>
<option value="Catagda-an">Catagda-an</option>
<option value="Del Pilar">Del Pilar</option>
<option value="Estaca">Estaca</option>
<option value="Ilaud">Ilaud</option>
<option value="Inaghuban">Inaghuban</option>
<option value="La Suerte">La Suerte</option>
<option value="Lumbay">Lumbay</option>
<option value="Lundag">Lundag</option>
<option value="Pamacsalan">Pamacsalan</option>
<option value="Poblacion">Poblacion</option>
<option value="Rizal">Rizal</option>
<option value="San Carlos">San Carlos</option>
<option value="San Isidro">San Isidro</option>
<option value="San Vicente">San Vicente</option>