<option value="Bayongan">Bayongan</option>
<option value="Bugang">Bugang</option>
<option value="Cabangahan">Cabangahan</option>
<option value="Caluasan">Caluasan</option>
<option value="Camanaga">Camanaga</option>
<option value="Cambangay Norte">Cambangay Norte</option>
<option value="Capayas">Capayas</option>
<option value="Corazon">Corazon</option>
<option value="Garcia">Garcia</option>
<option value="Hagbuyo">Hagbuyo</option>
<option value="Kagawasan">Kagawasan</option>
<option value="Mahayag">Mahayag</option>
<option value="Poblacion">Poblacion</option>
<option value="San Isidro">San Isidro</option>
<option value="San Jose">San Jose</option>
<option value="San Vicente">San Vicente</option>
<option value="Santo Niño">Santo Niño</option>
<option value="Tomoc">Tomoc</option>