<option value="Angilan">Angilan</option>
<option value="Bantolinao">Bantolinao</option>
<option value="Bicahan">Bicahan</option>
<option value="Bitaugan">Bitaugan</option>
<option value="Bungahan">Bungahan</option>
<option value="Canlaas">Canlaas</option>
<option value="Can-omay">Can-omay</option>
<option value="Cansibuan">Cansibuan</option>
<option value="Ceiling">Ceiling</option>
<option value="Danao">Danao</option>
<option value="Danicop">Danicop</option>
<option value="Mag-aso">Mag-aso</option>
<option value="Poblacion">Poblacion</option>
<option value="Quinapon-an">Quinapon-an</option>
<option value="Santo Rosario">Santo Rosario</option>
<option value="Tabuan">Tabuan</option>
<option value="Tagubaas">Tagubaas</option>
<option value="Tupas">Tupas</option>
<option value="Ubojan">Ubojan</option>
<option value="Viga">Viga</option>
<option value="Villa Aurora (Canoc-oc)">Villa Aurora (Canoc-oc)</option>