<option value="Bonifacio">Bonifacio</option>
<option value="Bugang Norte">Bugang Norte</option>
<option value="Bugang Sur">Bugang Sur</option>
<option value="Cabacnitan (Magsaysay)">Cabacnitan (Magsaysay)</option>
<option value="Cambigsi">Cambigsi</option>
<option value="Campagao">Campagao</option>
<option value="Cansumbol">Cansumbol</option>
<option value="Dagohoy">Dagohoy</option>
<option value="Owac">Owac</option>
<option value="Poblacion">Poblacion</option>
<option value="Quezon">Quezon</option>
<option value="Riverside">Riverside</option>
<option value="Rizal">Rizal</option>
<option value="Roxas">Roxas</option>
<option value="Subayon">Subayon</option>
<option value="Villa Aurora">Villa Aurora</option>
<option value="Villa Suerte">Villa Suerte</option>
<option value="Yanaya">Yanaya</option>
<option value="Zamora">Zamora</option>