<option value="Abucayan Norte">Abucayan Norte</option>
<option value="Abucayan Sur">Abucayan Sur</option>
<option value="Banlasan">Banlasan</option>
<option value="Bentig">Bentig</option>
<option value="Binogawan">Binogawan</option>
<option value="Bonbon">Bonbon</option>
<option value="Cabayugan">Cabayugan</option>
<option value="Cabudburan">Cabudburan</option>
<option value="Calunasan">Calunasan</option>
<option value="Camias">Camias</option>
<option value="Canguha">Canguha</option>
<option value="Catmonan">Catmonan</option>
<option value="Desamparados">Desamparados</option>
<option value="Kahayag">Kahayag</option>
<option value="Kinabag-an">Kinabag-an</option>
<option value="Labuon">Labuon</option>
<option value="Lawis">Lawis</option>
<option value="Liboron">Liboron</option>
<option value="Lomboy">Lomboy</option>
<option value="Lo-oc">Lo-oc</option>
<option value="Lucob">Lucob</option>
<option value="Madangog">Madangog</option>
<option value="Magtongtong">Magtongtong</option>
<option value="Mandaug">Mandaug</option>
<option value="Mantatao">Mantatao</option>
<option value="Sampoangon">Sampoangon</option>
<option value="San Isidro">San Isidro</option>
<option value="Santa Cruz">Santa Cruz</option>
<option value="Sojoton">Sojoton</option>
<option value="Talisay">Talisay</option>
<option value="Tinibgan">Tinibgan</option>
<option value="Tultugan">Tultugan</option>
<option value="Ulbujan">Ulbujan</option>