<option value="Abihid">Abihid</option>
<option value="Alemania">Alemania</option>
<option value="Baguhan">Baguhan</option>
<option value="Bakilid">Bakilid</option>
<option value="Balbalan">Balbalan</option>
<option value="Banban">Banban</option>
<option value="Bauhugan">Bauhugan</option>
<option value="Bilisan">Bilisan</option>
<option value="Cabagakian">Cabagakian</option>
<option value="Cabanbanan">Cabanbanan</option>
<option value="Cadap-agan">Cadap-agan</option>
<option value="Cambacol">Cambacol</option>
<option value="Cambayaon">Cambayaon</option>
<option value="Canhayupon">Canhayupon</option>
<option value="Canlambong">Canlambong</option>
<option value="Casingan">Casingan</option>
<option value="Catugasan">Catugasan</option>
<option value="Datag">Datag</option>
<option value="Guindaguitan">Guindaguitan</option>
<option value="Guingoyuran">Guingoyuran</option>
<option value="Ile">Ile</option>
<option value="Lapsaon">Lapsaon</option>
<option value="Limokon Ilaud">Limokon Ilaud</option>
<option value="Limokon Ilaya">Limokon Ilaya</option>
<option value="Luyo">Luyo</option>
<option value="Malijao">Malijao</option>
<option value="Oac">Oac</option>
<option value="Pagsa">Pagsa</option>
<option value="Pangihawan">Pangihawan</option>
<option value="Puangyuta">Puangyuta</option>
<option value="Sawang">Sawang</option>
<option value="Tangohay">Tangohay</option>
<option value="Taongon Cabatuan">Taongon Cabatuan</option>
<option value="Taongon Can-andam">Taongon Can-andam</option>
<option value="Tawid Bitaog">Tawid Bitaog</option>