<option value="Abijilan">Abijilan</option>
<option value="Antipolo">Antipolo</option>
<option value="Basiao">Basiao</option>
<option value="Cagwang">Cagwang</option>
<option value="Calma">Calma</option>
<option value="Cambuyo">Cambuyo</option>
<option value="Canayon East">Canayon East</option>
<option value="Canayon West">Canayon West</option>
<option value="Candanas">Candanas</option>
<option value="Candulao">Candulao</option>
<option value="Catmon">Catmon</option>
<option value="Cayam">Cayam</option>
<option value="Cupa">Cupa</option>
<option value="Datag">Datag</option>
<option value="Estaca">Estaca</option>
<option value="Libertad">Libertad</option>
<option value="Lungsodaan East">Lungsodaan East</option>
<option value="Lungsodaan West">Lungsodaan West</option>
<option value="Malinao">Malinao</option>
<option value="Manaba">Manaba</option>
<option value="Pasong">Pasong</option>
<option value="Poblacion East">Poblacion East</option>
<option value="Poblacion West">Poblacion West</option>
<option value="Sacaon">Sacaon</option>
<option value="Sampong">Sampong</option>
<option value="Tabuan">Tabuan</option>
<option value="Togbongon">Togbongon</option>
<option value="Ulbujan East">Ulbujan East</option>
<option value="Ulbujan West">Ulbujan West</option>
<option value="Victoria">Victoria</option>