<option value="Agape">Agape</option>
<option value="Alegria Norte">Alegria Norte</option>
<option value="Alegria Sur">Alegria Sur</option>
<option value="Bonbon">Bonbon</option>
<option value="Botoc Occidental">Botoc Occidental</option>
<option value="Botoc Oriental">Botoc Oriental</option>
<option value="Calvario">Calvario</option>
<option value="Concepcion">Concepcion</option>
<option value="Hinawanan">Hinawanan</option>
<option value="Las Salinas Norte">Las Salinas Norte</option>
<option value="Las Salinas Sur">Las Salinas Sur</option>
<option value="Palo">Palo</option>
<option value="Poblacion Ibabao">Poblacion Ibabao</option>
<option value="Poblacion Ubos">Poblacion Ubos</option>
<option value="Sagnap">Sagnap</option>
<option value="Tambangan">Tambangan</option>
<option value="Tangcasan Norte">Tangcasan Norte</option>
<option value="Tangcasan Sur">Tangcasan Sur</option>
<option value="Tayong Occidental">Tayong Occidental</option>
<option value="Tayong Oriental">Tayong Oriental</option>
<option value="Tocdog Dacu">Tocdog Dacu</option>
<option value="Tocdog Ilaya">Tocdog Ilaya</option>
<option value="Villalimpia">Villalimpia</option>
<option value="Yanangan">Yanangan</option>