<option value="Badbad Occidental">Badbad Occidental</option>
<option value="Badbad Oriental">Badbad Oriental</option>
<option value="Basdacu">Basdacu</option>
<option value="Basdio">Basdio</option>
<option value="Biasong">Biasong</option>
<option value="Bongco">Bongco</option>
<option value="Bugho">Bugho</option>
<option value="Cabacongan">Cabacongan</option>
<option value="Cabadug">Cabadug</option>
<option value="Cabug">Cabug</option>
<option value="Calayugan Norte">Calayugan Norte</option>
<option value="Calayugan Sur">Calayugan Sur</option>
<option value="Cambaquiz">Cambaquiz</option>
<option value="Campatud">Campatud</option>
<option value="Candaigan">Candaigan</option>
<option value="Canhangdon Occidental">Canhangdon Occidental</option>
<option value="Canhangdon Oriental">Canhangdon Oriental</option>
<option value="Canigaan">Canigaan</option>
<option value="Canmaag">Canmaag</option>
<option value="Canmanoc">Canmanoc</option>
<option value="Cansuagwit">Cansuagwit</option>
<option value="Cansubayon">Cansubayon</option>
<option value="Cantam-is Bago">Cantam-is Bago</option>
<option value="Cantam-is Baslay">Cantam-is Baslay</option>
<option value="Cantaongon">Cantaongon</option>
<option value="Cantumocad">Cantumocad</option>
<option value="Catagbacan Handig">Catagbacan Handig</option>
<option value="Catagbacan Norte">Catagbacan Norte</option>
<option value="Catagbacan Sur">Catagbacan Sur</option>
<option value="Cogon Norte">Cogon Norte</option>
<option value="Cogon Sur">Cogon Sur</option>
<option value="Cuasi">Cuasi</option>
<option value="Genomoan">Genomoan</option>
<option value="Lintuan">Lintuan</option>
<option value="Looc">Looc</option>
<option value="Mocpoc Norte">Mocpoc Norte</option>
<option value="Mocpoc Sur">Mocpoc Sur</option>
<option value="Moto Norte">Moto Norte</option>
<option value="Moto Sur">Moto Sur</option>
<option value="Nagtuang">Nagtuang</option>
<option value="Napo">Napo</option>
<option value="Nueva Vida">Nueva Vida</option>
<option value="Panangquilon">Panangquilon</option>
<option value="Pantudlan">Pantudlan</option>
<option value="Pig-ot">Pig-ot</option>
<option value="Pondol">Pondol</option>
<option value="Quinobcoban">Quinobcoban</option>
<option value="Sondol">Sondol</option>
<option value="Song-on">Song-on</option>
<option value="Talisay">Talisay</option>
<option value="Tan-awan">Tan-awan</option>
<option value="Tangnan">Tangnan</option>
<option value="Taytay">Taytay</option>
<option value="Ticugan">Ticugan</option>
<option value="Tiwi">Tiwi</option>
<option value="Tontonan">Tontonan</option>
<option value="Tubodacu">Tubodacu</option>
<option value="Tubodio">Tubodio</option>
<option value="Tubuan">Tubuan</option>
<option value="Ubayon">Ubayon</option>
<option value="Ubojan">Ubojan</option>