<option value="Agahay">Agahay</option>
<option value="Aliguay">Aliguay</option>
<option value="Anislag">Anislag</option>
<option value="Bayacabac">Bayacabac</option>
<option value="Bood">Bood</option>
<option value="Busao">Busao</option>
<option value="Cabawan">Cabawan</option>
<option value="Candavid">Candavid</option>
<option value="Dipatlong">Dipatlong</option>
<option value="Guiwanon">Guiwanon</option>
<option value="Jandig">Jandig</option>
<option value="Lagtangon">Lagtangon</option>
<option value="Lincod">Lincod</option>
<option value="Pagnitoan">Pagnitoan</option>
<option value="Poblacion">Poblacion</option>
<option value="Punsod">Punsod</option>
<option value="Punta Cruz">Punta Cruz</option>
<option value="San Isidro">San Isidro</option>
<option value="San Roque (Aghao)">San Roque (Aghao)</option>
<option value="San Vicente">San Vicente</option>
<option value="Tinibgan">Tinibgan</option>
<option value="Toril">Toril</option>