<option value="Abachanan">Abachanan</option>
<option value="Anibongan">Anibongan</option>
<option value="Bugsoc">Bugsoc</option>
<option value="Cahayag">Cahayag</option>
<option value="Canlangit">Canlangit</option>
<option value="Canta-ub">Canta-ub</option>
<option value="Casilay">Casilay</option>
<option value="Danicop">Danicop</option>
<option value="Dusita">Dusita</option>
<option value="La Union">La Union</option>
<option value="Lataban">Lataban</option>
<option value="Magsaysay">Magsaysay</option>
<option value="Man-od">Man-od</option>
<option value="Matin-ao">Matin-ao</option>
<option value="Poblacion">Poblacion</option>
<option value="Salvador">Salvador</option>
<option value="San Agustin">San Agustin</option>
<option value="San Isidro">San Isidro</option>
<option value="San Jose">San Jose</option>
<option value="San Juan">San Juan</option>
<option value="Santa Cruz">Santa Cruz</option>
<option value="Villa Garcia">Villa Garcia</option>