<option value="Banlasan">Banlasan</option>
<option value="Bongbong">Bongbong</option>
<option value="Catoogan">Catoogan</option>
<option value="Guinobatan">Guinobatan</option>
<option value="Hinlayagan Ilaud">Hinlayagan Ilaud</option>
<option value="Hinlayagan Ilaya">Hinlayagan Ilaya</option>
<option value="Kauswagan">Kauswagan</option>
<option value="Kinan-oan">Kinan-oan</option>
<option value="La Union">La Union</option>
<option value="La Victoria">La Victoria</option>
<option value="Mabuhay Cabigohan">Mabuhay Cabigohan</option>
<option value="Mahabgu">Mahabgu</option>
<option value="Manuel M. Roxas">Manuel M. Roxas</option>
<option value="Poblacion">Poblacion</option>
<option value="San Isidro">San Isidro</option>
<option value="San Vicente">San Vicente</option>
<option value="Santo Tomas">Santo Tomas</option>
<option value="Soom">Soom</option>
<option value="Tagum Norte">Tagum Norte</option>
<option value="Tagum Sur">Tagum Sur</option>